name: Deploy to Supabase
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'

      - name: Build
        run: hugo --minify --destination ./docs

      - name: Show Build Result
        run: ls -R ./docs  # 用于验证构建结果

      - name: Deploy to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          npm install -g supabase
          supabase login --key $SUPABASE_SERVICE_KEY
          supabase storage upload docs/* static-assets --project-ref $SUPABASE_URL
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-key: ${{ secrets.SUPABASE_ANON_KEY }}
          local-path: './public'
          remote-path: 'hugo-site'