name: Deploy to Supabase
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'

      - name: Build Hugo site
        run: hugo --minify

      - name: Upload to Supabase Storage
        uses: supabase/storage-cli-action@v1
        with:
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-key: ${{ secrets.SUPABASE_ANON_KEY }}
          local-path: './public'
          remote-path: 'hugo-site'